# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

# Theme
remote_theme: alshedivat/al-folio

title: "Paving the Way for Trustworthy Science Foundation Models" # the website title (if blank, full name will be used instead)
first_name:
middle_name:
last_name:
contact_note: >
  For questions about the workshop, please contact the organizers.
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Workshop on Trustworthy Science Foundation Models: Challenges and Frontiers @ NeurIPS 2025
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: trustworthy AI, science foundation models, NeurIPS, workshop, scientific AI, AI safety # add your own keywords or leave empty
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: 🔬 # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://alshedivat.github.io # the base hostname & protocol for your site
baseurl: /TrustSciFM # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: false # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
back_to_top: true # set to false to disable the back to top button

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo color theme
repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed # https://github.com/ryo-ma/github-profile-trophy

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true

# Dimensions
max_width: 930px

# TODO: add layout settings (single page vs. multi-page)

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# see https://schema.org/docs/faq.html for more information
serve_og_meta: false # Include Open Graph meta tags in the HTML head
serve_schema_org: false # Include Schema.org in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

# For Google Analytics, see https://support.google.com/analytics/answer/10447272?hl=en&ref_topic=14088998&sjid=5129943941510317771-SA#zippy=%2Cgoogle-sites
# and follow the instructions for Google Sites. You will need to create a Google Analytics property and copy the Google tag ID.
google_analytics: # your Google Analytics measurement ID (format: G-XXXXXXXXXX)
cronitor_analytics: # cronitor RUM analytics site ID (format: XXXXXXXXX)
pirsch_analytics: # your Pirsch analytics site ID (length 32 characters)
openpanel_analytics: # your Openpanel analytics client ID (format: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)

# For Google Search Console, see https://support.google.com/webmasters/answer/9008080?hl=en#meta_tag_verification&zippy=%2Chtml-tag
google_site_verification: # your google-site-verification ID (Google Search Console)
bing_site_verification: # out your bing-site-verification ID (Bing Webmaster)

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: al-folio # blog_name will be displayed in your blog page
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/
lsi: false # produce an index for related posts

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

related_blog_posts:
  enabled: true
  max_related: 5

# Giscus comments (RECOMMENDED)
# Follow instructions on https://giscus.app/ to setup for your repo to fill out the information below.
giscus:
  repo: # <your-github-user-name>/<your-github-repo-name>
  repo_id: # leave empty or specify your repo_id (see https://giscus.app/)
  category: Comments # name of the category under which discussions will be created
  category_id: # leave empty or specify your category_id (see https://giscus.app/)
  mapping: title # identify discussions by post title
  strict: 1 # use strict identification mode
  reactions_enabled: 1 # enable (1) or disable (0) emoji reactions
  input_position: bottom # whether to display input form below (bottom) or above (top) the comments
  theme: preferred_color_scheme # name of the color scheme (preferred works well with al-folio light/dark mode)
  emit_metadata: 0
  lang: en

# Disqus comments (DEPRECATED)
disqus_shortname: al-folio # put your disqus shortname
# https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# External sources.
# If you have blog posts published on medium.com or other external sources,
# you can display them in your blog by adding a link to the RSS feed.
external_sources:
  - name: medium.com
    rss_url: https://medium.com/@al-folio/feed
  - name: Google Blog
    posts:
      - url: https://blog.google/technology/ai/google-gemini-update-flash-ai-assistant-io-2024/
        published_date: 2024-05-14

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

newsletter:
  enabled: false
  endpoint: # your loops endpoint (e.g., https://app.loops.so/api/newsletter-form/YOUR-ENDPOINT)
  # https://loops.so/docs/forms/custom-form

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  books:
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
keep_files:
  - CNAME
  - .nojekyll

# Plug-ins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-include-cache

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier (Not supported by GitHub Pages)
# -----------------------------------------------------------------------------

# jekyll-minifier:
#   compress_javascript: false
#   exclude: ["robots.txt", "assets/js/search/*.js"]

# -----------------------------------------------------------------------------
# Terser (Not supported by GitHub Pages)
# -----------------------------------------------------------------------------

# terser:
#   compress:
#     drop_console: true

# -----------------------------------------------------------------------------
# Jekyll Archives (Not supported by GitHub Pages)
# -----------------------------------------------------------------------------

# jekyll-archives:
#   posts:
#     enabled: [year, tags, categories]
#     permalinks:
#       year: "/blog/:year/"
#       tags: "/blog/:type/:name/"
#       categories: "/blog/:type/:name/"
#   books:
#     enabled: [year, tags, categories]

display_tags: ["formatting", "images", "links", "math", "code", "blockquotes"] # these tags will be displayed on the front page of your blog
display_categories: ["external-services"] # these categories will be displayed on the front page of your blog

# -----------------------------------------------------------------------------
# Jekyll Scholar (Not supported by GitHub Pages)
# -----------------------------------------------------------------------------

# scholar:
#   last_name: [Einstein]
#   first_name: [Albert, A.]
#   style: apa
#   locale: en
#   source: /_bibliography/
#   bibliography: papers.bib
#   bibliography_template: bib
#   bibtex_filters: [latex, smallcaps, superscript]
#   replace_strings: true
#   join_strings: true
#   details_dir: bibliography
#   details_link: Details
#   query: "@*"
#   group_by: year
#   group_order: descending

# Display different badges withs stats for your publications
# Customize badge behavior in _layouts/bib.liquid
# enable_publication_badges:
#   altmetric: true
#   dimensions: true
#   google_scholar: true
#   inspirehep: true

# Filter out certain bibtex entry keywords used internally from the bib output
# filtered_bibtex_keywords:
#   [
#     abbr,
#     abstract,
#     additional_info,
#     altmetric,
#     annotation,
#     arxiv,
#     award,
#     award_name,
#     bibtex_show,
#     blog,
#     code,
#     google_scholar_id,
#     html,
#     inspirehep_id,
#     pdf,
#     poster,
#     preview,
#     selected,
#     slides,
#     supp,
#     video,
#     website,
#   ]

# Maximum number of authors to be shown for each publication (more authors are visible on click)
# max_author_limit: 3 # leave blank to always show all authors
# more_authors_animation_delay: 10 # more authors are revealed on click using animation; smaller delay means faster animation

# Enables publication thumbnails. If disabled, none of the publications will display thumbnails, even if specified in the bib entry.
# enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

# These are the defaults
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

# MAKE SURE imagemagick is installed and on your PATH before enabling imagemagick. In a terminal, run:
#   convert -version
imagemagick:
  enabled: false

# Lazy loading images
#   If you enable lazy loading, all images will add the loading="lazy" attribute.
#   This will make your site load faster, but it may not be supported in all browsers.
#   You can also set loading="" to other values for specific images to override the default behavior.
#   Options: "auto", "eager", "lazy"
#   See https://web.dev/browser-level-image-lazy-loading/ for more information.
lazy_loading_images: true # enables lazy loading of images (recommended)

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: false # enables google analytics
enable_cronitor_analytics: false # enables cronitor RUM analytics
enable_pirsch_analytics: false # enables Pirsch analytics (https://pirsch.io/)
enable_openpanel_analytics: false # enables Openpanel analytics (https://openpanel.dev/)
enable_google_verification: false # enables google site verification
enable_bing_verification: false # enables bing site verification
enable_masonry: true # enables automatic project cards arrangement
enable_math: true # enables math typesetting (uses MathJax)
enable_tooltips: false # enables automatic tooltip links generated for each section titles on pages and posts
enable_darkmode: true # enables switching between light/dark modes
enable_navbar_social: false # enables displaying social links in the navbar on the about page
enable_project_categories: true # enables categorization of projects into multiple categories
enable_medium_zoom: true # enables image zoom feature (as on medium.com)
enable_progressbar: true # enables a horizontal progress bar linked to the vertical scroll position
enable_video_embedding: false # enables video embedding for bibtex entries. If false, the button opens the video link in a new window.

# -----------------------------------------------------------------------------
# Library versions (Simplified for GitHub Pages)
# -----------------------------------------------------------------------------

# Most third-party libraries are disabled for GitHub Pages compatibility
# third_party_libraries:
#   download: false

# -----------------------------------------------------------------------------
# Get external JSON data (Not supported by GitHub Pages)
# -----------------------------------------------------------------------------

# jekyll_get_json:
#   - data: resume
#     json: assets/json/resume.json

# jsonresume:
#   - basics
#   - work
#   - education
#   - publications
#   - projects
#   - volunteer
#   - awards
#   - certificates
#   - skills
#   - languages
#   - interests
#   - references
